ALTER TABLE "Rating" ADD COLUMN IF NOT EXISTS "responsivenessScore" INTEGER DEFAULT 0;
ALTER TABLE "Rating" ADD COLUMN IF NOT EXISTS "solutionScore" INTEGER DEFAULT 0;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "centreId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "nip" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "fraksi" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "jabatan" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dapil" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isSync" BOOLEAN DEFAULT false;
